eureka:
  client:
    service-url:
      #魔术字符串后备值，为任何不表示首选项的客户端提供服务URL（即它是有用的默认值）
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: ribbonconsumer

server:
  port: 9000
